### ISSUE TITLE
Add a menu strip with File, About, and File->Exit

### ISSUE THREAD

**Issue by jwuavionix** [jwuavionix/CSVTOKMLConverter#3]
Add a menu strip to the application.  It should contain File and About at the top level with Exit under the file.  The file->exit should do just that.  The About should trigger a window pop-up form with information about the program, the program's version information along with the icon dressing.

**Comment by adamgoldsmith640** [comment]
Added a menu strip, File>Exit works, as does the About box. Uncertain on the About details though. For instance, is there a copyright?
