### ISSUE TITLE
Google Earth still not displaying data

### ISSUE THREAD

**Issue by jwuavionix** [jwuavionix/CSVTOKMLConverter#5]
Using the attached CSV file, I generated a KML file using the tool and then attempted to open the KML file in Google Earth.  The file was opened and points were displayed is a list (without names) under the places window but nothing was rendered on the map.  Not sure what the issue is but this is the main functionality for this tool so it needs to be tested until its working.  Also, see the attached screenshot to see the list of points.  Each point should have a name associated with it (either a row number or the timestamp for that row) instead of nothing.

[L1223173.zip](https://github.com/jwuavionix/CSVTOKMLConverter/files/1613283/L1223173.zip)
[Screenshot 2018-01-08 16.31.14.PDF](https://github.com/jwuavionix/CSVTOKMLConverter/files/1613287/Screenshot.2018-01-08.16.31.14.PDF)

**Comment by jwuavionix** [comment]
Any progress getting this issue resolved?  Have you been able to reproduce it?

**Comment by adamgoldsmith640** [comment]
The last two days have been pretty full, but I'm working on it now.

**Comment by adamgoldsmith640** [comment]
Tell me if this KML file does what you want. I generated it from within Google Earth, and pared away everything I thought had nothing to do with the bits you are wanting.
[My Places_skeletal.zip](https://github.com/jwuavionix/CSVTOKMLConverter/files/1624711/My.Places_skeletal.zip)

**Comment by jwuavionix** [comment]
Import this file, for each line in the CSV file, I'd like this type of display.  The Flight path needs to be covered by the "UAT 3d GeoAlt" type of display while the rest of the data should appear in the "UAT Airborne Compliant" type of display.

[A4BC3A-48013344.kml.zip](https://github.com/jwuavionix/CSVTOKMLConverter/files/1624857/A4BC3A-48013344.kml.zip)

**Comment by adamgoldsmith640** [comment]
Regarding the contents of the <style> elements at the top, is there any part of it, besides the name and description, that depends on the input file?

Also, I don't understand the second half of the names for the points. It kind of looks like a date, but not quite. Do you know what column it's being pulled from, or how it's generated?
Ex.: 21:03:08.445-10/9/1/3/2

**Comment by jwuavionix** [comment]
I’m not sure and I’m not at a point where I can look. Use your best
judgment and do what makes the most sense for the use cases.

**Comment by adamgoldsmith640** [comment]
I'm not aware of any formal use cases, so until you tell me otherwise, I'm assuming you are telling me to use my own judgement.

**Comment by jwuavionix** [comment]
The use case is this.

As I'm flying I'm running a device that logs all of this information.  Once
I land, I'd like to run the CSV file that was generated while I was flying
into this tool to convert it into a KML file that is easily viewed in
Google Earth.  It should show my flight path including altitude and as
icing on the cake, each point on the KML file should have all of the other
misc information from each row in the CSV file listed for reference.

Use the previously attached KML file as reference to generate something
similar.  It was generated with a different tool chain but is similar in
the fact it's a flight path displayed in google earth with points
displaying reference information.

**Comment by adamgoldsmith640** [comment]
I don't suppose you have the CSV version of the last file you attached here? I think a before and after kind of thing would help.

I also haven't been able to figure out units for altitude. Not entirely certain about timestamp units either - I've been assuming seconds since 1/1/1970, except that it's about a year off.

**Comment by jwuavionix** [comment]
No, that was a kml file generated from another tool from a different source
of data so it doesn’t have a csv file like ours that we can give you. It
was just a reference for the type of output we’re looking to generate.

The altitude would be most likely in ft but I’m not certain of that and I’m
sure you’ve tried that already.

I think the time is in gps format which would be referenced to the gps
epoch and not the Unix time epoch. However, these time references are 10
years and 6 days offset and doesn’t explain the 1yr offset your seeing.
